import type { Metadata } from "next";
import { Geist, Geist_Mono, Bai_Jamjuree } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const baiJamjuree = Bai_Jamjuree({
  weight: ["200", "400", "600", "700"],
  subsets: ["thai", "latin"],
  variable: "--font-bai-jamjuree", // ชื่อต้องตรงกับใน globals.css
});

export const metadata: Metadata = {
  title: "SmartBizz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // ${geistSans.variable}
  return (
    <html lang="en">
      <body className={`${baiJamjuree.variable} font-sans`}>{children}</body>
    </html>
  );
}
